name: bioimage
channels:
    - defaults
    - conda-forge
    - antonkulaga
    - bioconda
dependencies:
    - python=3.9
    - scikit-image=0.18.3
    - pims=0.5
    - opencv=4.5.3
    - jpype1=1.3.0
    - scikit-image
    - setuptools
    - matplotlib
    - pandas
    - twine
    - tifffile
    - numpy
    - pip:
          - pycomfort==0.0.9
          - beartype